### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by ThatOneCalculator** [IgKh/katvan#1]
I currently have to run the AppImage with `QT_QPA_PLATFORM=xcb ./Katvan-0.3.0-linux-x86_64_856eb0606a2294b824aab4970420c2fc.AppImage`. If there's any chance you could add Wayland support that'd be great!

**Comment by IgKh** [comment]
Hi, the 0.4.0 AppImage just released today has the generic Wayland Qt platform plugin and client library bundled, so should work natively under any compositor otherwise supported by Qt. Please try it out if you'd like.
