### ISSUE TITLE
Ability to hide line numbers

### ISSUE THREAD

**Issue by ThatOneCalculator** [IgKh/katvan#2]
I think having line numbers on both the left and right of the editor is a bit much, especially when they don't match the color scheme

![image](https://github.com/IgKh/katvan/assets/44733677/e56821e7-9d8f-415d-ab59-ba57d403fe81)

**Comment by ThatOneCalculator** [comment]
In my opinion, at least with left-to-right, it looks a lot better with one gutter

![image](https://github.com/IgKh/katvan/assets/44733677/95a3ce2e-609d-4ab4-a44f-7ce5b93aa17b)

**Comment by ThatOneCalculator** [comment]
Thank you for the reply! It's not very interesting -- thankfully I'm not an econ major ^^

**Comment by IgKh** [comment]
Both issues addressed in version 0.5.0:
- Number of line number gutters is configurable (two, one on the primary side or none)
- Gutter is painted with system palette background color, so won't look awkward on a dark style
