### ISSUE TITLE
Instructions for general Linux

### ISSUE THREAD

**Issue by boredsquirrel** [IgKh/katvan#3]
Hi, Fedora has no package, and typst has no binaries, but it can be added to the path anyways.

A generic Linux guide would be

```
# install rustup according to https://www.rust-lang.org/tools/install
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# add it to your path, example for bash
echo "PATH=$PATH:$HOME/.cargo/bin" >> ~/.bashrc

cd ~
cargo init
cargo add typst
```

Afaik this is even cross platform. Rust and other languages prefer to control their packages on their own, and this is completely independend of system packages, making updates faster and stuff more reproducible.

The official typst page links to some repo list, so installing as system package. I am not sure if these instructions may be added here, or there.

**Comment by IgKh** [comment]
No longer relevant, since Typst is now bundled with Katvan itself.
